// const adjectives = [
//   "Luxury",
//   "Cozy",
//   "Elegant",
//   "Modern",
//   "Classic",
//   "Charming",
//   "Trendy",
//   "Spacious",
//   "Comfortable",
//   "Opulent",
//   "Quaint",
//   "Stylish",
//   "Sleek",
//   "Grand",
//   "Sophisticated",
//   "Chic",
//   "Inviting",
//   "Premium",
//   "Upscale",
//   "Rustic",
//   "Majestic",
//   "Refined",
//   "Contemporary",
//   "Boutique",
//   "Serene",
//   "Exquisite",
//   "Lavish",
//   "Elegant",
//   "Luxurious",
//   "Trendy",
//   "Homely",
//   "Exclusive",
//   "Unique",
//   "Stylish",
//   "Distinctive",
//   "Picturesque",
//   "Serene",
//   "Vibrant",
//   "Elegant",
//   "Majestic",
//   "Polished",
//   "Timeless",
//   "Classic",
//   "Modern",
//   "Contemporary",
//   "Stylish",
//   "Cozy",
//   "Comfortable",
//   "Classy",
//   "High-end",
//   "Refined",
//   "Charming",
//   "Lush",
//   "Spacious",
//   "Opulent",
//   "Grand",
//   "Trendy",
//   "Exclusive",
//   "Sophisticated",
//   "Elegant",
//   "Inviting",
//   "Luxurious",
//   "Charming",
//   "Premium",
//   "Upscale",
//   "Exclusive",
//   "Refined",
//   "Modern",
//   "Elegant",
//   "Sophisticated",
//   "Distinctive",
//   "Unique",
//   "Vibrant",
//   "Picturesque",
//   "Homely",
//   "Quaint",
//   "Boutique",
//   "Sleek",
//   "Stylish",
//   "Luxurious",
//   "Elegant",
//   "Exquisite",
//   "Opulent",
//   "High-end",
//   "Modern",
//   "Contemporary",
//   "Refined",
//   "Trendy",
// ]

// const nouns = [
//   "Suites",
//   "Inn",
//   "Lodge",
//   "Resort",
//   "Hotel",
//   "Motel",
//   "Villa",
//   "Hostel",
//   "Bungalows",
//   "Chalets",
//   "Cabins",
//   "Cottages",
//   "Retreat",
//   "Residences",
//   "Palace",
//   "Castle",
//   "Haven",
//   "Oasis",
//   "Estates",
//   "Manor",
//   "Pavilion",
//   "Sanctuary",
//   "Quarters",
//   "Hacienda",
//   "Dwelling",
//   "Flat",
//   "Apartment",
//   "Loft",
//   "Bungalows",
//   "Penthouse",
//   "Condo",
//   "Cabana",
//   "House",
//   "Dome",
//   "Bungalow",
//   "Suite",
//   "Room",
//   "Complex",
//   "Homestead",
//   "Retreat",
//   "Villa",
//   "Grove",
//   "Haven",
//   "Suite",
//   "Residence",
//   "Park",
//   "Lodge",
//   "Refuge",
//   "Abode",
//   "Villa",
//   "Mansion",
//   "Inn",
//   "Cabin",
//   "Home",
//   "Chateau",
//   "Condominium",
//   "Hostel",
//   "Hotel",
//   "Bungalow",
//   "Dwellings",
//   "Studio",
//   "Estate",
//   "Casita",
//   "Flat",
//   "Residences",
//   "Retreat",
//   "Suite",
//   "Apartment",
//   "Motel",
//   "Resort",
//   "Lodge",
//   "Retreat",
//   "Mansion",
//   "Condo",
//   "Chalet",
//   "Manor",
//   "Palace",
// ]

// const getRandomElement = (arr: string[]) => arr[Math.floor(Math.random() * arr.length)]

// const generateUniqueHotelTypes = (count: number) => {
//   const hotelTypes = new Set<string>() // Use a Set to store unique names

//   while (hotelTypes.size < count) {
//     const adjective = getRandomElement(adjectives)
//     const noun = getRandomElement(nouns)
//     // const theme = getRandomElement(themes)
//     // const suffix = getRandomElement(suffixes)

//     const newType = `${adjective} ${noun}` // Modify this pattern as needed

//     hotelTypes.add(newType)
//   }

//   return Array.from(hotelTypes)
// }

export const hotelTypes = [
  "Boutique",
  "Luxury",
  "Budget",
  "Business",
  "Resort",
  "Airport",
  "Extended Stay",
  "Hostel",
  "Bed and Breakfast",
  "Motels",
  "Eco-Friendly",
  "Pet-Friendly",
  "Spa",
  "Historic",
  "All-Inclusive",
]
export const hotelFacilities:string[] = [
  "Free Wi-Fi",
  "Pool",
  "Gym",
  "Breakfast",
  "Room Service",
  "Spa",
  "Business Center",
  "Concierge",
  "Shuttle",
  "Restaurant",
]
